### ISSUE TITLE
Swipe is not working on Windows Phone 8

### ISSUE THREAD

**Issue by Zeneixe** [AidanZealley/off.canvas#8]
Plus page scrolling on the main site is insanely slow on my Lumia 620!

**Comment by AidanZealley** [comment]
Hi, thanks for letting me know :)

I'm currently really tied up on other projects which is why I haven't managed to work much on this lately but I am planning a new version that should solve a few bugs by being simpler, one of those bugs being the scrolling.

**Comment by Zeneixe** [comment]
OK, cheers :)
